### PR TITLE
Fix idle follower ack delay

### PR DESCRIPTION
**Pull request by tylertreat**
Fix issue #102 by having the leader notify followers when there is new
data available after the follower has caught up with the leader's log
end offset.

This also introduces a new config `replica.max.idle.wait` which
controls the max amount of time an idle follower will wait before making
a replication request. The primary purpose of this is to ensure timely
check-ins with the leader for health checking.

### CODE REVIEW

**Comment by paddybyers** [comment]
Sorry for the long delay.

The most illustrative test case is a scenario where we have:

- a single stream, bound to a single NATS subject, and a single consumer of the stream;
- a collection of publishers aiming to achieve a sustained publish rate of 10KHz - in these tests there are 100 publishers, each publishing at 100Hz;
- a NATS cluster and Liftbridge cluster comprising 3 x m5.large EC2 instances, in the same AZ. That is, each instance has one NATS process and one Liftbridge process;
- streams are persisted to EBS volumes;
- replication factor is 3;
- min in-sync replicas is 2;
- ack policy is ALL.

In each test we're measuring the distribution of the acknowledgement time experienced by each publisher, and the reception time for the subscriber, from the time of publication to NATS. Messages are streamed continuously for 60s.

All times are in seconds.

### `master` branch

AckTimeStats:
- Minimum: 0.06316
- Maximum: 0.36401
- Mean: 0.22462
- StandardDeviation: 0.06375
- Quantile25: 0.17480
- Quantile50: 0.23811
- Quantile75: 0.27805
- Quantile97: 0.31147
- Quantile99: 0.31660

ReceptionTimeStats:
- Minimum: 0.07055
- Maximum: 0.35918
- Mean: 0.23153
- StandardDeviation: 0.06080
- Quantile25: 0.18447
- Quantile50: 0.24424
- Quantile75: 0.28212
- Percentile97: 0.31455
- Percentile99: 0.32074

### `fix_idle_follower_lag` branch

AckTimeStats:
- Minimum: 0.00082
- Maximum: 0.05429
- Mean: 0.00324
- StandardDeviation: 0.00347
- Quantile25: 0.00176
- Quantile50: 0.00222
- Quantile75: 0.00308
- Percentile97: 0.01235
- Percentile99: 0.01889

ReceptionTimeStats:
- Minimum: 0.00081
- Maximum: 0.05927
- Mean: 0.00355
- StandardDeviation: 0.00400
- Quantile25: 0.00184
- Quantile50: 0.00235
- Quantile75: 0.00331
- Percentile97: 0.01416
- Percentile99: 0.02173

**Comment by tylertreat** [comment]
@paddybyers Thanks for sharing the results.

Out of curiosity, are you publishing straight to NATS or publishing through Liftbridge's synchronous publish API?

Is performance sufficient for your use case?

**Comment by paddybyers** [comment]
> Out of curiosity, are you publishing straight to NATS or publishing through Liftbridge's synchronous publish API?

We've been benchmarking both and, in the interests of seeing the liftbridge performance with the minimum of encumbrances, using publishing direct to NATS as the reference point. We haven't committed to either mechanism yet.

> Is performance sufficient for your use case?

Yes, what we're seeing with these results is definitely encouraging, and it's good enough that we can proceed with Liftbridge as a design assumption.

But as always with these things, I'm also curious to find out what now dominates: if we can replicate, persist, and deliver a message to a subscriber in sub 1ms, so why do some messages take up to 60ms? However, that's not so much a concern as it is an opportunity, and we probably won't get to look into it in detail until we've got some other work done. If you have thoughts/insights into that, then I'd be interested to hear them.

**Comment by tylertreat** [comment]
>We've been benchmarking both and, in the interests of seeing the liftbridge performance with the minimum of encumbrances, using publishing direct to NATS as the reference point. We haven't committed to either mechanism yet.

Makes sense. Right now Liftbridge only has a sync publish API which means it's no good for high-throughput cases. I intend to add an async one in the near future. Obviously, you will still have the extra hop with this, so for the most performance-sensitive cases, going straight to NATS is best.

> But as always with these things, I'm also curious to find out what now dominates: if we can replicate, persist, and deliver a message to a subscriber in sub 1ms, so why do some messages take up to 60ms? However, that's not so much a concern as it is an opportunity, and we probably won't get to look into it in detail until we've got some other work done. If you have thoughts/insights into that, then I'd be interested to hear them.

Totally, there is lots of room for improvement. :) I will need to spend some time digging into performance. For _throughput_, one thought is batching on the publish and subscribe sides. The tricky bit on the publish side is the default 1MB payload limit in NATS, but this can be adjusted in NATS config. I need to spend some time looking at batching to see how much that improves throughput. For _latency_, there are a number of things I'd like to look at.

But for now I'll merge this—thanks again for the feedback and testing.

**Pull request merged**
