### PR TITLE
add logging features

### PR DESCRIPTION
**Pull request by chrislee87**
log retention by message age, log retention by number of messages, log compaction

### CODE REVIEW

**Comment by ppizarro** [comment]
Maybe we can change the layout of the project by predicting other binaries.

As a suggestion we could create the "cmd" directory and move the server directory into it.

Then we could move the "log" package to the root of the project since it would be used by other binaries.

We could rename the server.go file to main.go

Other packages that are unique to the server could be moved to the internal folder inside "cmd/server"

Well, the layout of the project would look like this:

liftbridge/
  log/
    logger.go
  cmd/
    server/
	  main.go
	  internal/

**Comment by tylertreat** [comment]
@ppizarro I'm not sure I follow. Why would the log package be used by binaries other than Liftbridge?

**Comment by ppizarro** [comment]
oh my fault. The idea is that it could be used just by other liftbridge packages or binaries like a liftbridge-cli.
```
liftbridge/
  internal/ (common packages used by all liftbridge binaries)
    log/
      logger.go (interface and implementation)
  cmd/
    liftbridge/ (server)
	  main.go
	  internal/ (code used just by server)
    liftbridge-cli/
          main.go
```
And at the root of the project could be only the packages that would be exported.

**Comment by tylertreat** [comment]
Closing this since I think log management should be handled out of process, as discussed in #1.

**Pull request closed without merging**
