### PR TITLE
Support NATS TLS

### PR DESCRIPTION
**Pull request by LaPetiteSouris**
To support NATS TLS config, refer to #228 

Changes:

- [x]  Parse `cert` and `key` from config file
- [x]  Parse `pem` (CARoot) from config file
- [x]  Add test for parsing `cert` and `key` file
- [x]  Add test for parsing `pem` file
- [ ]  Add a integration test case with embedded NATS  (Not going to do)
- [x] Update documentation

How do you think we should test this feature ? Manually ? Should we set up an embedded NATS with `cert/key/pem` and try to do a normal publish/subscribe ?

### CODE REVIEW

**Comment by tylertreat** [comment]
> How do you think we should test this feature ? Manually ? Should we set up an embedded NATS with cert/key/pem and try to do a normal publish/subscribe ?

I don't think it's worth testing that TLS works correctly with the NATS client and server. What we _should_ test is that we correctly parse the config information from the config file.

**Comment by tylertreat** [comment]
Code changes lgtm otherwise!

**Comment by LaPetiteSouris** [comment]
> Code changes lgtm otherwise!

Just update the docs and add `caroot.pem` file into the unit test.

**Comment by tylertreat** [comment]
Thanks!

**Pull request merged**
