### PR TITLE
Support subscription as an ISR replica

### PR DESCRIPTION
**Pull request by LaPetiteSouris**
### Context

Related to issue https://github.com/liftbridge-io/liftbridge/issues/103

Liftbridge server accepts `SubscribeRequest` as an ISR replica if the client explicitly requests to do so.

### Implementation:
Explicitly verify request client.SubscribeRequest if it contains option client.SubscribeRequest.ReadReplica. If so, then server the request even when the server is acting as an ISR replica instead of the leader.

### Required PR to merge before:

on client side: https://github.com/liftbridge-io/go-liftbridge/pull/52
on API side: https://github.com/liftbridge-io/liftbridge-api/pull/22

### CODE REVIEW

**Comment by tylertreat** [comment]
Mind adding the new `ReadISRReplica` subscription option to the client implementation docs [here](https://github.com/liftbridge-io/liftbridge/blob/master/documentation/client_implementation.md#subscribe)? Additionally, it would probably be good to add a note about the option to the implementation notes [here](https://github.com/liftbridge-io/liftbridge/blob/master/documentation/client_implementation.md#subscribe-implementation).

**Comment by LaPetiteSouris** [comment]
> Mind adding the new `ReadISRReplica` subscription option to the client implementation docs [here](https://github.com/liftbridge-io/liftbridge/blob/master/documentation/client_implementation.md#subscribe)? Additionally, it would probably be good to add a note about the option to the implementation notes [here](https://github.com/liftbridge-io/liftbridge/blob/master/documentation/client_implementation.md#subscribe-implementation).

Done.

**Comment by tylertreat** [comment]
Looks like needs to update to newly merged github.com/liftbridge-io/liftbridge-api/go dependency?

**Comment by LaPetiteSouris** [comment]
> Looks like needs to update to newly merged github.com/liftbridge-io/liftbridge-api/go dependency?

It also needs this to be updated https://github.com/liftbridge-io/go-liftbridge. I think we should wait for `go-liftbridge` to be merged and update `go.mod` of this PR

**Comment by LaPetiteSouris** [comment]
> Looks like needs to update to newly merged github.com/liftbridge-io/liftbridge-api/go dependency?

Done. Builds are fixed, except for coverage .

**Pull request merged**
